version: "3"
services:
    runserver:
        build: .
        #network_mode: bridge
        #volumes:
        #    - .:/auto
        container_name: runserver
        ports:
            - "8000:8000"
        depends_on:
            - database
        command: python /auto/manage.py runserver 0.0.0.0:8000 
        networks:
            - minitel
networks:
    minitel:
