# Generated by Django 3.1.1 on 2020-10-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='CIBLE',
            field=models.CharField(choices=[('lacentrale', 'lacentrale')], max_length=15),
        ),
    ]
