# Generated by Django 3.1.1 on 2020-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20201020_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATTERN', models.URLField(max_length=20)),
                ('TARGET', models.URLField(max_length=20)),
            ],
        ),
    ]
