# Generated by Django 3.1.1 on 2020-10-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_target'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Target',
            new_name='Cible',
        ),
        migrations.RenameField(
            model_name='cible',
            old_name='PATTERN',
            new_name='CIBLE',
        ),
        migrations.RenameField(
            model_name='cible',
            old_name='TARGET',
            new_name='DOMAINE',
        ),
    ]
