# Generated by Django 3.1.1 on 2020-10-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_auto_20201021_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='CIBLE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.cible'),
        ),
    ]
