# Generated by Django 3.1.1 on 2020-11-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_cible_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cible',
            name='NOTE',
        ),
    ]
