# Generated by Django 3.1.1 on 2020-11-09 10:33

from django.db import migrations



def set_target_lacentrale(apps, schema_editor):
    Cible = apps.get_model('scrapper', 'Cible')
    lacentrale = Cible(DOMAINE='www.lacentrale.fr', CIBLE='lacentrale')
    lacentrale.save()
    
def set_target_leboncoin(apps, schema_editor):
    Cible = apps.get_model('scrapper', 'Cible')
    leboncoin = Cible(DOMAINE='www.leboncoin.fr', CIBLE='leboncoin')
    leboncoin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_remove_cible_note'),
    ]

    operations = [
        migrations.RunPython(set_target_lacentrale),
        migrations.RunPython(set_target_leboncoin),
    ]
