version: "3"
services:
    database:
        image: mariadb
        container_name: database
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=autodb
        hostname: 'database'
    runserver:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        container_name: runserver
        ports:
            - "8000:8000"
        depends_on:
            - database
