version: "3"
services:
    database:
        image: mariadb
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=autodb
    auto:
        build: .
        ports:
            - "8080:8080"
            - "8000:8000"
            - "50000:50000"
        
    
