# Generated by Django 3.1.1 on 2020-09-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MARQUE', models.CharField(blank=True, max_length=20)),
                ('MODELE', models.CharField(blank=True, max_length=20)),
                ('KM', models.FloatField(blank=True)),
                ('DIN', models.FloatField(blank=True)),
                ('PRIX', models.FloatField(blank=True)),
                ('ENERGIE', models.CharField(choices=[('ESSENCE', 'ESSENCE'), ('DIESEL', 'DIESEL')], default='ESSENCE', max_length=10)),
                ('ANNEE', models.IntegerField(blank=True)),
                ('DATE', models.DateField()),
                ('CODEPOSTAL', models.IntegerField(blank=True)),
                ('URL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.url')),
            ],
        ),
    ]
