# Generated by Django 3.1.1 on 2020-09-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=500)),
                ('MARQUE', models.CharField(blank=True, max_length=20)),
                ('MODELE', models.CharField(blank=True, max_length=20)),
                ('KM', models.FloatField(blank=True)),
                ('DIN', models.FloatField(blank=True)),
                ('PRIX', models.FloatField(blank=True)),
                ('ENERGIE', models.CharField(choices=[('ESSENCE', 'ESSENCE'), ('DIESEL', 'DIESEL')], default='ESSENCE', max_length=10)),
                ('ANNEE', models.IntegerField(blank=True)),
                ('DATE', models.DateField()),
                ('CODEPOSTAL', models.IntegerField(blank=True)),
            ],
        ),
    ]
