# Generated by Django 3.1.1 on 2020-09-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=500)),
                ('STATUS', models.CharField(choices=[('ATTENTE', 'ATTENTE'), ('VALIDE', 'VALIDE'), ('ERREUR', 'ERREUR')], default='ATTENTE', max_length=10)),
                ('DATE', models.DateField(auto_now_add=True)),
                ('CIBLE', models.CharField(max_length=15)),
            ],
        ),
    ]
