# Generated by Django 3.1.1 on 2020-10-24 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_auto_20201021_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='DATECRT',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
